on:
  push:

jobs:
  steampipe-csv-init:

    env:
      STEAMPIPE_LOG_LEVEL: trace

    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "csv" {
              plugin = "csv"
              paths = [ "*.csv" ]
            }

      - name: List tables in CSV schema (before plugin list)
        run: steampipe query list_tables_in_csv_schema.sql

      - name: List Steampipe plugins
        run: steampipe plugin list

      - name: List tables in CSV schema (after plugin list)
        run: steampipe query list_tables_in_csv_schema.sql

      - name: Upload Steampipe logs
        uses: actions/upload-artifact@v4
        with:
          name: steampipe-logs
          path: |
            /home/runner/.steampipe/logs/
            /home/runner/.steampipe/config/
          retention-days: 1
          include-hidden-files: true
