on:
  push:

jobs:
  init-information-schema:

    env:
      STEAMPIPE_LOG_LEVEL: trace

    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "csv" {
              plugin = "csv"
              paths = [ "*.csv" ]
            }

      - name: List tables in CSV schema (before plugin list)
        run: steampipe query list_tables_in_csv_schema.sql

      - name: List Steampipe plugins
        run: steampipe plugin list

      - name: List tables in CSV schema (after plugin list)
        run: steampipe query list_tables_in_csv_schema.sql

  report-errors:

    env:
      STEAMPIPE_LOG_LEVEL: trace

    runs-on: ubuntu-latest

    steps:

      - name: Set up Steampipe without CSV paths
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "csv" {
              plugin = "csv"
            }

      - name: List Steampipe plugins (shows CSV error)
        run: steampipe plugin list

      - name: Delete previous installation
        run: rm -rf /home/runner/.steampipe

      - name: Setup Steampipe with CSV paths
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "csv" {
              plugin = "csv"
              paths = [ "*.csv" ]
            }

      - name: List Steampipe plugins
        run: steampipe plugin list
